CREATE OR REPLACE TRIGGER BOA_BILLING_LOAD_QUEUE_TRG
BEFORE INSERT ON BOA_BILLING_LOAD_QUEUE
FOR EACH ROW
DECLARE
  P_ID   number;
  P_DATE DATE;
BEGIN
  
  SELECT BOA_BILLING_LOAD_QUEUE_SEQ.nextval, TRUNC(SYSDATE)
    INTO P_ID, P_DATE
    FROM dual; 
    
    INSERT INTO LOAD_QUEUE_TOSEND 
    VALUES ( P_ID);
         
    :new.PID      := P_id;
    :new.ENTRYDTE := p_date;
END;
/
