CREATE OR REPLACE TRIGGER BOA_BILLABLE_WORKORDERS_TRG
BEFORE INSERT ON BOA_BILLABLE_WORKORDERS_PID
FOR EACH ROW
DECLARE
  P_KEY   number;
  P_DATE DATE;
BEGIN

  SELECT BOA_BILLABLE_WO_SEQ.nextval
    INTO P_KEY
    FROM dual;

    :new.PKEY      := P_KEY;
END;
/
