CREATE OR REPLACE TRIGGER IPP$LIBRARIAN.LA_PENDING_REJECTIONS_BI
BEFORE INSERT ON LA_PENDING_REJECTIONS
FOR EACH ROW
DECLARE
  P_LOAD_ID       number;
BEGIN

        IF ( :new.LOAD_ID IS NULL) THEN 
            SELECT LA_PENDING_REJECTIONS_SEQ.NEXTVAL
            INTO P_LOAD_ID
            FROM DUAL;

            :new.LOAD_ID := P_LOAD_ID;
        END IF;
        

END;
/
