CREATE OR REPLACE TRIGGER SCHEMA_VARIABLES_BITRG
BEFORE INSERT ON SCHEMA_VARIABLES
FOR EACH ROW
DECLARE
  P_ID    number;

BEGIN

    IF ( :new.PID is null)
    THEN
        SELECT SCHEMA_VARIABLES_SEQ.NEXTVAL
        INTO P_ID
        FROM DUAL;

        :new.PID := P_ID;
    END IF;
END;
/
